local data = {
	humanName = "test",
	width = 30,
	height = 17,
    customVictoryText = "You've explored the entire island.  Now this one is more like it!",
	cameraPos = {
		[2] = 9.3,
		[1] = 18,
	},
	tileDeck = {
		[1] = {
			woodcutter = 3,
			sawmill = 1,
			mill = 1,
			farm = 6,
			fishery = 1,
			barracks = 2,
			town = 7,
		},
		[2] = {
			woodcutter = 4,
			sawmill = 2,
			mill = 1,
			farm = 6,
			fishery = 2,
			barracks = 2,
			town = 7,
		},
	},
	hints = {
		[1] = {
			text = "- WASD (or Arrow Keys) to move the camera.\n- Ctrl+R to restart the game at any time.\n- Ctrl+N/Ctrl+P to skip to the next or previous level.\n\nOutposts are dismantled when there are no longer any unscouted lands in range.",
			size = {3.2, 1.1},
			pos = {
				[1] = 17.95,
				[2] = 1.6,
			},
		},
	},
	tiles = {
		[1] = {
			extraData = {
				armySize = 10,
				invasionIndex = 2,
			},
			pos = {
				[1] = 6,
				[2] = 11,
			},
			def = "invasion",
		},
		[2] = {
			extraData = {
				armySize = 4,
				invasionIndex = 1,
			},
			pos = {
				[1] = 14,
				[2] = 9,
			},
			def = "invasion",
		},
		[3] = {
			def = "town",
			pos = {
				[1] = 17,
				[2] = 10,
			},
		},
		[4] = {
			def = "farm",
			pos = {
				[1] = 18,
				[2] = 10,
			},
		},
		[5] = {
			def = "town",
			pos = {
				[1] = 21,
				[2] = 11,
			},
		},
		[6] = {
			def = "fishery",
			pos = {
				[1] = 22,
				[2] = 11,
			},
		},
		[7] = {
			def = "fishery",
			pos = {
				[1] = 22,
				[2] = 10,
			},
		},
	},
	terrain = {
		[1] = {
			[7] = "water",
			[8] = "water",
			[9] = "water",
		},
		[2] = {
			[5] = "water",
			[6] = "water",
			[7] = "grass",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "water",
			[13] = "water",
		},
		[3] = {
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "grass",
			[7] = "grass",
			[8] = "forest",
			[9] = "forest",
			[10] = "water",
			[11] = "mountain",
			[12] = "mountain",
			[13] = "mountain",
			[14] = "mountain",
			[15] = "mountain",
		},
		[4] = {
			[1] = "water",
			[2] = "water",
			[3] = "water",
			[4] = "water",
			[5] = "mountain",
			[6] = "grass",
			[7] = "grass",
			[8] = "forest",
			[9] = "forest",
			[10] = "grass",
			[11] = "desert",
			[12] = "desert",
			[13] = "desert",
			[14] = "desert",
			[15] = "mountain",
		},
		[5] = {
			[1] = "water",
			[2] = "water",
			[3] = "desert",
			[4] = "desert",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "forest",
			[9] = "grass",
			[10] = "desert",
			[11] = "desert",
			[12] = "mountain",
			[13] = "mountain",
			[14] = "desert",
			[15] = "mountain",
			[16] = "water",
		},
		[6] = {
			[1] = "water",
			[2] = "water",
			[3] = "desert",
			[4] = "grass",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "desert",
			[12] = "mountain",
			[13] = "mountain",
			[14] = "desert",
			[15] = "mountain",
			[16] = "water",
		},
		[7] = {
			[2] = "water",
			[3] = "water",
			[4] = "desert",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "desert",
			[12] = "desert",
			[13] = "desert",
			[14] = "desert",
			[15] = "mountain",
		},
		[8] = {
			[2] = "water",
			[3] = "water",
			[4] = "forest",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "forest",
			[12] = "mountain",
			[13] = "desert",
			[14] = "desert",
			[15] = "mountain",
		},
		[9] = {
			[3] = "water",
			[4] = "forest",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "forest",
			[11] = "mountain",
			[12] = "mountain",
			[13] = "mountain",
			[14] = "mountain",
			[15] = "mountain",
		},
		[10] = {
			[3] = "water",
			[4] = "water",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "forest",
			[11] = "water",
			[12] = "water",
			[14] = "mountain",
			[15] = "mountain",
		},
		[11] = {
			[2] = "water",
			[3] = "water",
			[4] = "water",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "water",
			[12] = "water",
			[13] = "water",
			[14] = "mountain",
		},
		[12] = {
			[3] = "water",
			[4] = "forest",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "mountain",
			[12] = "mountain",
			[13] = "mountain",
			[14] = "mountain",
		},
		[13] = {
			[3] = "water",
			[4] = "grass",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "mountain",
			[13] = "mountain",
			[14] = "mountain",
		},
		[14] = {
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "forest",
			[11] = "grass",
			[12] = "grass",
			[13] = "mountain",
			[14] = "mountain",
			[15] = "mountain",
		},
		[15] = {
			[5] = "water",
			[6] = "grass",
			[7] = "grass",
			[8] = "forest",
			[9] = "forest",
			[10] = "forest",
			[11] = "grass",
			[12] = "grass",
			[13] = "mountain",
			[14] = "mountain",
			[15] = "mountain",
		},
		[16] = {
			[4] = "water",
			[5] = "desert",
			[6] = "grass",
			[7] = "grass",
			[8] = "forest",
			[9] = "forest",
			[10] = "forest",
			[11] = "grass",
			[12] = "grass",
			[13] = "mountain",
			[14] = "mountain",
		},
		[17] = {
			[4] = "water",
			[5] = "desert",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "forest",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "mountain",
			[14] = "mountain",
			[15] = "water",
		},
		[18] = {
			[4] = "water",
			[5] = "water",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "mountain",
			[14] = "mountain",
			[15] = "water",
		},
		[19] = {
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "forest",
			[14] = "forest",
			[15] = "water",
		},
		[20] = {
			[4] = "water",
			[5] = "mountain",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "forest",
			[13] = "forest",
			[14] = "water",
			[15] = "water",
		},
		[21] = {
			[4] = "water",
			[5] = "mountain",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "forest",
			[13] = "forest",
			[14] = "water",
		},
		[22] = {
			[3] = "water",
			[4] = "water",
			[5] = "mountain",
			[6] = "mountain",
			[7] = "grass",
			[8] = "desert",
			[9] = "desert",
			[10] = "desert",
			[11] = "grass",
			[12] = "forest",
			[13] = "water",
			[14] = "water",
		},
		[23] = {
			[3] = "water",
			[4] = "water",
			[5] = "mountain",
			[6] = "mountain",
			[7] = "forest",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "desert",
			[12] = "forest",
			[13] = "water",
		},
		[24] = {
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "forest",
			[7] = "forest",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "desert",
			[12] = "water",
			[13] = "water",
		},
		[25] = {
			[4] = "water",
			[5] = "water",
			[6] = "forest",
			[7] = "water",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "water",
			[12] = "water",
		},
		[26] = {
			[4] = "water",
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "water",
			[12] = "water",
		},
		[27] = {
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[8] = "water",
			[9] = "water",
			[10] = "water",
		},
		[28] = {
			[6] = "water",
			[7] = "water",
			[8] = "water",
			[9] = "water",
			[10] = "water",
		},
		[29] = {
			[9] = "water",
		},
	},
	doodads = {
	},
	invasionMask = {
		[1] = {
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
		},
		[2] = {
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 2,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[3] = {
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 2,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[4] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 2,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[5] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 2,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[6] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 2,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[7] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 2,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[8] = {
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 1,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[9] = {
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 1,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[10] = {
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 1,
			[11] = 2,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
			[16] = 2,
		},
		[11] = {
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 1,
			[11] = 1,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
		},
		[12] = {
			[2] = 1,
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 1,
			[11] = 1,
			[12] = 2,
			[13] = 2,
			[14] = 2,
			[15] = 2,
		},
		[13] = {
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 1,
			[11] = 1,
			[13] = 2,
			[14] = 2,
		},
		[14] = {
			[3] = 1,
			[4] = 1,
			[5] = 1,
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
			[10] = 1,
			[14] = 2,
		},
		[15] = {
			[6] = 1,
			[7] = 1,
			[8] = 1,
			[9] = 1,
		},
	},
}

return data
