local data = {
	humanName = "test",
	width = 20,
	height = 25,
	cameraPos = {
		[2] = 8,
		[1] = 12,
	},
	tileDeck = {
		[1] = {
			town = 6,
		},
		[2] = {
			town = 4,
		},
	},
	tiles = {
	},
	terrain = {
		[7] = {
			[10] = "forest",
			[11] = "forest",
		},
		[8] = {
			[5] = "water",
			[7] = "water",
			[8] = "forest",
			[10] = "forest",
			[11] = "forest",
			[12] = "mountain",
		},
		[9] = {
			[4] = "water",
			[5] = "water",
			[6] = "forest",
			[7] = "mountain",
			[8] = "grass",
			[9] = "desert",
			[10] = "desert",
			[11] = "forest",
			[12] = "forest",
			[13] = "forest",
		},
		[10] = {
			[4] = "water",
			[5] = "water",
			[6] = "desert",
			[7] = "grass",
			[8] = "desert",
			[9] = "desert",
			[10] = "desert",
			[11] = "forest",
			[12] = "forest",
			[13] = "mountain",
		},
		[11] = {
			[3] = "water",
			[4] = "water",
			[5] = "desert",
			[6] = "desert",
			[7] = "grass",
			[8] = "water",
			[9] = "desert",
			[10] = "desert",
			[11] = "desert",
			[13] = "desert",
		},
		[12] = {
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "desert",
			[7] = "desert",
			[8] = "desert",
			[9] = "desert",
			[10] = "desert",
			[11] = "desert",
			[12] = "desert",
			[13] = "desert",
		},
		[13] = {
			[3] = "water",
			[4] = "water",
			[5] = "grass",
			[6] = "grass",
			[7] = "desert",
			[8] = "desert",
			[9] = "desert",
			[10] = "desert",
			[11] = "desert",
			[12] = "grass",
			[13] = "desert",
		},
		[14] = {
			[4] = "water",
			[5] = "water",
			[6] = "mountain",
			[7] = "desert",
			[8] = "desert",
			[9] = "desert",
			[10] = "water",
			[11] = "grass",
			[12] = "forest",
		},
		[15] = {
			[4] = "water",
			[5] = "water",
			[6] = "mountain",
			[7] = "water",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "mountain",
		},
		[16] = {
			[4] = "water",
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "water",
		},
		[17] = {
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[8] = "water",
		},
	},
	doodads = {
	},
	invasionMask = {
	},
}

return data
