local data = {
	tiles = {
	},
	terrain = {
		[0] = {
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[8] = "water",
			[12] = "water",
		},
		[1] = {
			[1] = "water",
			[2] = "water",
			[3] = "water",
			[4] = "water",
			[5] = "mountain",
			[6] = "mountain",
			[7] = "mountain",
			[8] = "mountain",
			[9] = "water",
			[10] = "water",
			[11] = "water",
			[12] = "water",
		},
		[2] = {
			[0] = "water",
			[1] = "water",
			[2] = "water",
			[3] = "grass",
			[4] = "grass",
			[5] = "grass",
			[6] = "mountain",
			[7] = "mountain",
			[8] = "mountain",
			[9] = "mountain",
			[10] = "mountain",
			[11] = "water",
			[12] = "water",
		},
		[3] = {
			[1] = "water",
			[2] = "water",
			[3] = "desert",
			[4] = "grass",
			[5] = "grass",
			[6] = "grass",
			[7] = "forest",
			[8] = "mountain",
			[9] = "mountain",
			[10] = "mountain",
			[11] = "mountain",
			[12] = "water",
		},
		[4] = {
			[1] = "water",
			[2] = "desert",
			[3] = "desert",
			[4] = "desert",
			[5] = "desert",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "forest",
			[10] = "mountain",
			[11] = "mountain",
			[12] = "water",
		},
		[5] = {
			[1] = "water",
			[2] = "desert",
			[3] = "desert",
			[4] = "desert",
			[5] = "desert",
			[6] = "desert",
			[7] = "grass",
			[8] = "grass",
			[9] = "forest",
			[10] = "forest",
			[11] = "mountain",
			[12] = "water",
			[13] = "water",
		},
		[6] = {
			[1] = "water",
			[2] = "desert",
			[3] = "desert",
			[4] = "desert",
			[5] = "desert",
			[6] = "grass",
			[7] = "grass",
			[8] = "forest",
			[9] = "forest",
			[10] = "forest",
			[11] = "mountain",
			[12] = "water",
			[13] = "water",
		},
		[7] = {
			[0] = "water",
			[1] = "water",
			[2] = "desert",
			[3] = "grass",
			[4] = "desert",
			[5] = "forest",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "forest",
			[10] = "forest",
			[11] = "mountain",
			[12] = "water",
			[13] = "water",
		},
		[8] = {
			[0] = "water",
			[1] = "water",
			[2] = "grass",
			[3] = "grass",
			[4] = "grass",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "forest",
			[10] = "grass",
			[11] = "mountain",
			[12] = "water",
			[13] = "water",
		},
		[9] = {
			[0] = "water",
			[1] = "water",
			[2] = "grass",
			[3] = "grass",
			[4] = "grass",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "mountain",
			[12] = "water",
		},
		[10] = {
			[1] = "water",
			[2] = "water",
			[3] = "forest",
			[4] = "forest",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "mountain",
			[12] = "water",
			[-1] = "water",
		},
		[11] = {
			[0] = "water",
			[1] = "water",
			[2] = "water",
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[8] = "water",
			[9] = "grass",
			[10] = "grass",
			[11] = "mountain",
			[12] = "water",
			[-1] = "water",
		},
		[12] = {
			[1] = "water",
			[2] = "water",
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[8] = "water",
			[9] = "water",
			[10] = "water",
			[11] = "water",
			[12] = "water",
		},
		[13] = {
			[2] = "water",
			[3] = "water",
			[4] = "water",
			[5] = "water",
			[6] = "water",
			[7] = "water",
			[9] = "water",
			[10] = "water",
		},
		[14] = {
			[7] = "water",
			[8] = "water",
			[9] = "water",
		},
	},
	tileDeck = {
		[2] = {
			woodcutter = 8,
			sawmill = 6,
			farm = 8,
			town = 12,
		},
		[1] = {
			woodcutter = 8,
			sawmill = 6,
			farm = 8,
			town = 12,
		},
	},
	humanName = "test level",
	width = 12,
	height = 12,
}

return data
