local data = {
	tileDeck = {
		[1] = {
			woodcutter = 4,
			quarry = 4,
			tavern = 9,
			blacksmith = 4,
			sawmill = 3,
			mine = 4,
			barracks = 5,
			mill = 2,
			fishery = 6,
			tower = 10,
			town = 6,
			farm = 7,
			fountain = 9,
		},
		[2] = {
			woodcutter = 4,
			quarry = 4,
			tavern = 9,
			blacksmith = 4,
			sawmill = 3,
			mine = 4,
			barracks = 5,
			mill = 2,
			fishery = 6,
			tower = 10,
			town = 6,
			farm = 7,
			fountain = 9,
		},
	},
	width = 20,
	height = 20,
	cameraPos = {
		[2] = 10,
		[1] = 10,
	},
	humanName = "test",
	terrain = {
		[4] = {
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[5] = {
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[6] = {
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[7] = {
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[8] = {
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[9] = {
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[10] = {
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[11] = {
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[12] = {
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[13] = {
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[14] = {
			[4] = "grass",
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[15] = {
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[15] = "grass",
		},
		[16] = {
			[5] = "grass",
			[6] = "grass",
			[7] = "grass",
			[8] = "grass",
			[9] = "grass",
			[10] = "grass",
			[11] = "grass",
			[12] = "grass",
			[13] = "grass",
			[14] = "grass",
			[17] = "mountain",
			[18] = "mountain",
			[19] = "mountain",
			[20] = "mountain",
		},
		[17] = {
			[20] = "mountain",
			[18] = "grass",
			[17] = "mountain",
			[19] = "grass",
			[10] = "grass",
			[9] = "grass",
		},
		[18] = {
			[17] = "mountain",
			[18] = "grass",
			[20] = "mountain",
			[19] = "grass",
		},
		[19] = {
			[17] = "mountain",
			[18] = "mountain",
			[20] = "mountain",
			[19] = "mountain",
		},
	},
	invasionMask = {
	},
	doodads = {
	},
	tiles = {
		[1] = {
			pos = {
				[1] = 7,
				[2] = 14,
			},
			def = "sawmill",
		},
		[2] = {
			pos = {
				[1] = 7,
				[2] = 13,
			},
			def = "tavern",
		},
		[3] = {
			pos = {
				[1] = 8,
				[2] = 14,
			},
			def = "tavern",
		},
		[4] = {
			pos = {
				[1] = 8,
				[2] = 13,
			},
			def = "farm",
		},
		[5] = {
			pos = {
				[1] = 8,
				[2] = 12,
			},
			def = "town",
		},
		[6] = {
			pos = {
				[1] = 8,
				[2] = 11,
			},
			def = "town",
		},
		[7] = {
			pos = {
				[1] = 8,
				[2] = 10,
			},
			def = "town",
		},
		[8] = {
			pos = {
				[1] = 8,
				[2] = 9,
			},
			def = "town",
		},
		[9] = {
			pos = {
				[1] = 9,
				[2] = 13,
			},
			def = "farm",
		},
		[10] = {
			pos = {
				[1] = 10,
				[2] = 13,
			},
			def = "town",
		},
		[11] = {
			pos = {
				[1] = 10,
				[2] = 10,
			},
			def = "woodcutter",
		},
		[12] = {
			pos = {
				[1] = 10,
				[2] = 9,
			},
			def = "woodcutter",
		},
		[13] = {
			pos = {
				[1] = 11,
				[2] = 11,
			},
			def = "tavern",
		},
		[14] = {
			pos = {
				[1] = 11,
				[2] = 10,
			},
			def = "sawmill",
		},
		[15] = {
			pos = {
				[1] = 11,
				[2] = 9,
			},
			def = "sawmill",
		},
		[16] = {
			pos = {
				[1] = 17,
				[2] = 19,
			},
			def = "plenty",
		},
		[17] = {
			pos = {
				[1] = 17,
				[2] = 18,
			},
			def = "plenty",
		},
		[18] = {
			pos = {
				[1] = 18,
				[2] = 18,
			},
			def = "plenty",
		},
	},
}

return data
